### ISSUE TITLE
Not actually writing anything to comosdb graph

### ISSUE THREAD

**Issue by shaunybrown** [syedhassaanahmed/databricks-notebooks#1]
I have ran your code as is (with the addition of my connection details) on my databricks cluster but nothing is actually being written in the Cosmos DB graph instance I have set up. 

When I search the graph I get:

Failed to auto-select root node. Reason:undefined
Query result is empty
Connecting to wss://*****.gremlin.cosmosdb.azure.com:443 as /dbs/graphdb/colls/NewGraph
Execute query: g.V()

**Comment by syedhassaanahmed** [comment]
Hi @shaunybrown Have you attached the [azure-cosmosdb-spark connector uber jar](http://repo1.maven.org/maven2/com/microsoft/azure/azure-cosmosdb-spark_2.3.0_2.11/1.2.0/) as a library to your Databricks cluster as described in the notebook?

Also before writing to Cosmos DB, the notebook tries to `display()` vertices and edges that are going to be written. What output do you see from those cells in the notebook?

**Comment by shaunybrown** [comment]
Think there was something wrong with my cosmos build, redeployed it and working fine. Apologies!
