### ISSUE TITLE
graph data frame  writing issue

### ISSUE THREAD

**Issue by samynathan17** [syedhassaanahmed/databricks-notebooks#3]
Hi i'm trying to same example to load cosmos Gremlin db i got error for IllegalArgumentException: "Invalid JSON String: ''"

![graphdberror](https://user-images.githubusercontent.com/16590988/66459356-804a7980-ea92-11e9-96da-2599b9ae0007.PNG)

**Comment by syedhassaanahmed** [comment]
Hi @samynathan17 I can see from the `Endpoint` that you're using `wss://` which is a Gremlin protocol endpoint. The Cosmos DB Spark Connector doesn't use Gremlin and instead relies on the underlying SQL API to connect. You should use the `https://` endpoint as also highlighted in the [Graph Write Sample](https://github.com/syedhassaanahmed/databricks-notebooks/blob/e40a60feea523158fe3e6b081bbc2df93bc0f82f/graph_write_cosmosdb.py#L112)

**Comment by samynathan17** [comment]
Hi @syedhassaanahmed ,

Thanks for your replay now its working for me .
